export const INITIAL_USERS = [
  {
    id: 'usr_1',
    name: 'Alex Johnson',
    email: 'alex.johnson@family.local',
    role: 'family_admin', // family_admin | family_member | non_family
    memberType: 'family', // family | non_family
    avatarColor: '#6366f1',
    avatarInitials: 'AJ',
    pin: '1234',
    relationship: 'Head of Household / Parent',
  },
  {
    id: 'usr_2',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@family.local',
    role: 'family_member',
    memberType: 'family',
    avatarColor: '#10b981',
    avatarInitials: 'SJ',
    pin: '2345',
    relationship: 'Parent / Co-head',
  },
  {
    id: 'usr_3',
    name: 'David Johnson',
    email: 'david.johnson@family.local',
    role: 'family_member',
    memberType: 'family',
    avatarColor: '#f59e0b',
    avatarInitials: 'DJ',
    pin: '3456',
    relationship: 'College Student / Dependent',
  },
  {
    id: 'usr_4',
    name: 'Mark Vance',
    email: 'mark.vance@private.com',
    role: 'non_family',
    memberType: 'non_family',
    avatarColor: '#a855f7',
    avatarInitials: 'MV',
    pin: '9999',
    relationship: 'Independent / Non-Family Member',
  },
];

export const INITIAL_ACCOUNTS = [
  // Alex Johnson Accounts
  {
    id: 'acc_1',
    userId: 'usr_1',
    name: 'Chase Main Checking',
    bankName: 'JPMorgan Chase',
    type: 'checking', // checking | savings | credit | investment | cash | loan
    balance: 8450.25,
    accountNumberMask: '•••• 4821',
    color: '#3b82f6',
    currency: 'USD',
  },
  {
    id: 'acc_2',
    userId: 'usr_1',
    name: 'Fidelity High Yield Savings',
    bankName: 'Fidelity Investments',
    type: 'savings',
    balance: 34200.00,
    accountNumberMask: '•••• 9102',
    color: '#10b981',
    currency: 'USD',
  },
  {
    id: 'acc_3',
    userId: 'usr_1',
    name: 'Amex Gold Preferred',
    bankName: 'American Express',
    type: 'credit',
    balance: -1420.50,
    accountNumberMask: '•••• 1004',
    color: '#f59e0b',
    currency: 'USD',
  },
  {
    id: 'acc_4',
    userId: 'usr_1',
    name: 'Vanguard Index Portfolio',
    bankName: 'Vanguard',
    type: 'investment',
    balance: 62450.00,
    accountNumberMask: '•••• 7731',
    color: '#8b5cf6',
    currency: 'USD',
  },

  // Sarah Johnson Accounts
  {
    id: 'acc_5',
    userId: 'usr_2',
    name: 'Bank of America Checking',
    bankName: 'Bank of America',
    type: 'checking',
    balance: 5120.80,
    accountNumberMask: '•••• 3391',
    color: '#06b6d4',
    currency: 'USD',
  },
  {
    id: 'acc_6',
    userId: 'usr_2',
    name: 'Capital One Emergency Reserve',
    bankName: 'Capital One',
    type: 'savings',
    balance: 21500.00,
    accountNumberMask: '•••• 8820',
    color: '#ec4899',
    currency: 'USD',
  },
  {
    id: 'acc_7',
    userId: 'usr_2',
    name: 'Apple Card Cashback',
    bankName: 'Goldman Sachs',
    type: 'credit',
    balance: -480.20,
    accountNumberMask: '•••• 5519',
    color: '#64748b',
    currency: 'USD',
  },

  // David Johnson Accounts
  {
    id: 'acc_8',
    userId: 'usr_3',
    name: 'Discover Student Checking',
    bankName: 'Discover Bank',
    type: 'checking',
    balance: 1450.00,
    accountNumberMask: '•••• 2049',
    color: '#f97316',
    currency: 'USD',
  },
  {
    id: 'acc_9',
    userId: 'usr_3',
    name: 'College Savings Wallet',
    bankName: 'Ally Bank',
    type: 'savings',
    balance: 3800.50,
    accountNumberMask: '•••• 6612',
    color: '#84cc16',
    currency: 'USD',
  },

  // Mark Vance (Non-Family Member) Accounts
  {
    id: 'acc_10',
    userId: 'usr_4',
    name: 'Wells Fargo Premier Checking',
    bankName: 'Wells Fargo',
    type: 'checking',
    balance: 12800.00,
    accountNumberMask: '•••• 9911',
    color: '#a855f7',
    currency: 'USD',
  },
  {
    id: 'acc_11',
    userId: 'usr_4',
    name: 'Marcus Vault Savings',
    bankName: 'Goldman Sachs',
    type: 'savings',
    balance: 45000.00,
    accountNumberMask: '•••• 4433',
    color: '#d946ef',
    currency: 'USD',
  },
];

export const INITIAL_CATEGORIES = [
  // Income categories
  { id: 'cat_inc_1', name: 'Salary & Compensation', type: 'income', icon: 'Briefcase', color: '#10b981', isSystem: true },
  { id: 'cat_inc_2', name: 'Freelance & Consulting', type: 'income', icon: 'Laptop', color: '#06b6d4', isSystem: false },
  { id: 'cat_inc_3', name: 'Investment Dividends', type: 'income', icon: 'TrendingUp', color: '#8b5cf6', isSystem: false },
  { id: 'cat_inc_4', name: 'Allowance / Transfer', type: 'income', icon: 'Gift', color: '#f59e0b', isSystem: false },

  // Expense categories
  { id: 'cat_exp_1', name: 'Housing & Rent', type: 'expense', icon: 'Home', color: '#6366f1', budgetLimit: 2500, isSystem: true },
  { id: 'cat_exp_2', name: 'Groceries & Market', type: 'expense', icon: 'ShoppingCart', color: '#10b981', budgetLimit: 900, isSystem: true },
  { id: 'cat_exp_3', name: 'Dining Out & Cafes', type: 'expense', icon: 'Utensils', color: '#f43f5e', budgetLimit: 600, isSystem: false },
  { id: 'cat_exp_4', name: 'Utilities & Internet', type: 'expense', icon: 'Zap', color: '#f59e0b', budgetLimit: 400, isSystem: false },
  { id: 'cat_exp_5', name: 'Transportation & Fuel', type: 'expense', icon: 'Car', color: '#06b6d4', budgetLimit: 350, isSystem: false },
  { id: 'cat_exp_6', name: 'Entertainment & Subs', type: 'expense', icon: 'Tv', color: '#a855f7', budgetLimit: 250, isSystem: false },
  { id: 'cat_exp_7', name: 'Healthcare & Fitness', type: 'expense', icon: 'Activity', color: '#ec4899', budgetLimit: 300, isSystem: false },
  { id: 'cat_exp_8', name: 'Shopping & Apparel', type: 'expense', icon: 'ShoppingBag', color: '#f97316', budgetLimit: 500, isSystem: false },
  { id: 'cat_exp_9', name: 'Education & Books', type: 'expense', icon: 'BookOpen', color: '#3b82f6', budgetLimit: 400, isSystem: false },
];

export const INITIAL_TRANSACTIONS = [
  // Alex Johnson Transactions
  {
    id: 'tx_1',
    userId: 'usr_1',
    accountId: 'acc_1',
    categoryId: 'cat_inc_1',
    type: 'income',
    amount: 6800.00,
    payee: 'TechCorp Inc (Direct Deposit)',
    date: '2026-10-01',
    note: 'Bi-monthly salary payout',
    tags: ['salary', 'direct-deposit'],
    isRecurring: true,
  },
  {
    id: 'tx_2',
    userId: 'usr_1',
    accountId: 'acc_1',
    categoryId: 'cat_exp_1',
    type: 'expense',
    amount: 2200.00,
    payee: 'Highland Luxury Apartments',
    date: '2026-10-01',
    note: 'Monthly Apartment Rent',
    tags: ['housing', 'fixed'],
    isRecurring: true,
  },
  {
    id: 'tx_3',
    userId: 'usr_1',
    accountId: 'acc_3',
    categoryId: 'cat_exp_2',
    type: 'expense',
    amount: 245.80,
    payee: 'Whole Foods Market',
    date: '2026-10-02',
    note: 'Weekly organic grocery run',
    tags: ['groceries', 'family'],
    isRecurring: false,
  },
  {
    id: 'tx_4',
    userId: 'usr_1',
    accountId: 'acc_3',
    categoryId: 'cat_exp_3',
    type: 'expense',
    amount: 128.50,
    payee: 'Bistro Deluxe',
    date: '2026-09-28',
    note: 'Family Friday Dinner',
    tags: ['dining', 'family'],
    isRecurring: false,
  },
  {
    id: 'tx_5',
    userId: 'usr_1',
    accountId: 'acc_2',
    categoryId: 'cat_inc_3',
    type: 'income',
    amount: 430.00,
    payee: 'Vanguard Dividend Payment',
    date: '2026-09-25',
    note: 'Quarterly index fund distribution',
    tags: ['investing'],
    isRecurring: true,
  },

  // Sarah Johnson Transactions
  {
    id: 'tx_6',
    userId: 'usr_2',
    accountId: 'acc_5',
    categoryId: 'cat_inc_1',
    type: 'income',
    amount: 5400.00,
    payee: 'BioHealth Solutions',
    date: '2026-10-01',
    note: 'Monthly payroll deposit',
    tags: ['salary'],
    isRecurring: true,
  },
  {
    id: 'tx_7',
    userId: 'usr_2',
    accountId: 'acc_5',
    categoryId: 'cat_exp_4',
    type: 'expense',
    amount: 185.00,
    payee: 'City Energy & Utilities',
    date: '2026-09-29',
    note: 'Electric & Gas bill',
    tags: ['utilities'],
    isRecurring: true,
  },
  {
    id: 'tx_8',
    userId: 'usr_2',
    accountId: 'acc_7',
    categoryId: 'cat_exp_7',
    type: 'expense',
    amount: 140.00,
    payee: 'Equinox Fitness Club',
    date: '2026-09-27',
    note: 'Monthly gym membership',
    tags: ['fitness'],
    isRecurring: true,
  },
  {
    id: 'tx_9',
    userId: 'usr_2',
    accountId: 'acc_7',
    categoryId: 'cat_exp_2',
    type: 'expense',
    amount: 189.30,
    payee: 'Trader Joe\'s',
    date: '2026-09-30',
    note: 'Pantry essentials',
    tags: ['groceries'],
    isRecurring: false,
  },

  // David Johnson Transactions
  {
    id: 'tx_10',
    userId: 'usr_3',
    accountId: 'acc_8',
    categoryId: 'cat_inc_4',
    type: 'income',
    amount: 500.00,
    payee: 'Alex Johnson (Parents Transfer)',
    date: '2026-10-01',
    note: 'Monthly College Allowance',
    tags: ['allowance'],
    isRecurring: true,
  },
  {
    id: 'tx_11',
    userId: 'usr_3',
    accountId: 'acc_8',
    categoryId: 'cat_exp_9',
    type: 'expense',
    amount: 210.00,
    payee: 'Campus Bookstore',
    date: '2026-09-26',
    note: 'Computer Science Textbooks',
    tags: ['education', 'college'],
    isRecurring: false,
  },
  {
    id: 'tx_12',
    userId: 'usr_3',
    accountId: 'acc_8',
    categoryId: 'cat_exp_3',
    type: 'expense',
    amount: 42.10,
    payee: 'University Pizza & Cafe',
    date: '2026-09-29',
    note: 'Late night study snack with classmates',
    tags: ['dining'],
    isRecurring: false,
  },

  // Mark Vance (Non-Family Member) Transactions
  {
    id: 'tx_13',
    userId: 'usr_4',
    accountId: 'acc_10',
    categoryId: 'cat_inc_2',
    type: 'income',
    amount: 8500.00,
    payee: 'Apex Digital Systems',
    date: '2026-10-01',
    note: 'Retainer payment for Q4 Architecture',
    tags: ['consulting', 'private'],
    isRecurring: true,
  },
  {
    id: 'tx_14',
    userId: 'usr_4',
    accountId: 'acc_10',
    categoryId: 'cat_exp_1',
    type: 'expense',
    amount: 3100.00,
    payee: 'Penthouse Condo Lease',
    date: '2026-10-01',
    note: 'Monthly luxury lease payment',
    tags: ['rent'],
    isRecurring: true,
  },
  {
    id: 'tx_15',
    userId: 'usr_4',
    accountId: 'acc_10',
    categoryId: 'cat_exp_5',
    type: 'expense',
    amount: 145.00,
    payee: 'Tesla Supercharger Network',
    date: '2026-09-28',
    note: 'EV Charging and highway toll pass',
    tags: ['transport'],
    isRecurring: false,
  },
];
